DROP TABLE IF EXISTS DOCS;
DROP TABLE IF EXISTS QUERIES;
DROP TABLE IF EXISTS QRELS;
DROP VIEW IF EXISTS JOINED;
DROP TABLE IF EXISTS QUERIES_MODEL_0;
DROP TABLE IF EXISTS QRELS_MODEL_0;
DROP TABLE IF EXISTS QUERIES_MODEL_1;
DROP TABLE IF EXISTS QRELS_MODEL_1;


CREATE TABLE DOCS(
ID NUMBER PRIMARY KEY,
DOC_ID NUMBER,
DATA TEXT);

CREATE TABLE QUERIES(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DATA TEXT);

CREATE TABLE QRELS(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DOC_ID NUMBER);

CREATE TABLE QUERIES_MODEL_0(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DATA TEXT);

CREATE TABLE QUERIES_MODEL_1(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DATA TEXT);

CREATE TABLE QRELS_MODEL_0(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DOC_ID NUMBER);

CREATE TABLE QRELS_MODEL_1(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DOC_ID NUMBER);

CREATE UNIQUE INDEX DOCS_D_ID ON DOCS(DOC_ID);
CREATE UNIQUE INDEX QUERIES_Q_ID ON QUERIES(QUERY_ID);
CREATE UNIQUE INDEX QUERIES_Q0_ID ON QUERIES_MODEL_0(QUERY_ID);
CREATE UNIQUE INDEX QUERIES_Q1_ID ON QUERIES_MODEL_1(QUERY_ID);

CREATE INDEX QRELS_D_ID ON QRELS(DOC_ID);
CREATE INDEX QRELS_Q_ID ON QRELS(QUERY_ID);

CREATE INDEX QRELS_D0_ID ON QRELS_MODEL_0(DOC_ID);
CREATE INDEX QRELS_Q0_ID ON QRELS_MODEL_0(QUERY_ID);

CREATE INDEX QRELS_D1_ID ON QRELS_MODEL_1(DOC_ID);
CREATE INDEX QRELS_Q_1ID ON QRELS_MODEL_1(QUERY_ID);


CREATE VIEW JOINED AS
SELECT QRELS.ID ID, Q.QUERY_ID, Q.DATA QUERY_DATA, D.DOC_ID, D.DATA DOC_DATA FROM QRELS
LEFT JOIN DOCS D ON QRELS.DOC_ID = D.DOC_ID
LEFT JOIN QUERIES Q ON QRELS.QUERY_ID = Q.QUERY_ID;
