DROP TABLE IF EXISTS DOCS;
DROP TABLE IF EXISTS QUERIES;
DROP TABLE IF EXISTS QRELS;
DROP TABLE IF EXISTS JOINED;

CREATE TABLE DOCS(
ID NUMBER PRIMARY KEY,
DOC_ID NUMBER,
DATA TEXT);

CREATE TABLE QUERIES(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DATA TEXT);

CREATE TABLE QRELS(
ID NUMBER PRIMARY KEY,
QUERY_ID NUMBER,
DOC_ID NUMBER);

CREATE UNIQUE INDEX DOCS_D_ID ON DOCS(DOC_ID);
CREATE UNIQUE INDEX QUERIES_Q_ID ON QUERIES(QUERY_ID);

CREATE INDEX QRELS_D_ID ON QRELS(DOC_ID);
CREATE INDEX QRELS_Q_ID ON QRELS(QUERY_ID);

CREATE VIEW JOINED AS
SELECT QRELS.ID ID, Q.QUERY_ID, Q.DATA, D.DOC_ID, D.DATA FROM QRELS
LEFT JOIN DOCS D ON QRELS.DOC_ID = D.DOC_ID
LEFT JOIN QUERIES Q ON QRELS.QUERY_ID = Q.QUERY_ID;
